_target_: src.models.pointnet_module.PointNetPartSegModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 2  # 10
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 20
  gamma: 0.7

net:
  _target_: src.models.pointnet_module.PointNetPartSeg
  num_classes: 50
  in_channels: 6

# compile model for faster training with pytorch 2.0
compile: false
